### ISSUE TITLE
More than 6 videos in Chrome

### ISSUE THREAD

**Issue by kalmerrautam** [cbopp-art/lightcase#103]
I have 15 videos on my page (hosted locally) played inside Lightcase.
After playing 6'th one of them (in whatever order) rest of them won't open anymore.

I read that Chrome will not support more than 6 video tags on one page. I have set preload="none", but it doesn't help.

Is there any way for avoiding that problem?

**Comment by cbopp-art** [comment]
Has nothing to do with lightcase itself since this is a restriction of the Browser chrome/chromium.

More information about that issue can be found here:
https://bugs.chromium.org/p/chromium/issues/detail?id=162627&q=HTML5%20audio%20limit&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified
