### ISSUE TITLE
video autoplay is not working

### ISSUE THREAD

**Issue by tapash** [cbopp-art/lightcase#126]
This is my demo page, but with settings 'autoplay' is not working.....

<a href="https://www.youtube.com/embed/6v2L2UGZJAM" data-rel="lightcase">Youtube video</a>

<script type="text/javascript">
	$('a[data-rel^=lightcase]').lightcase({
	  video: {
	    autoplay:true
	 }
});

**Comment by cbopp-art** [comment]
Hi!
Youtube video is embed via iframe because it is external source. Thus, you have to set the autoplay parameter directly to the url as it is provided as setting by youtube. I think this must be something like `&autoplay=1`

Type `video` is used if your video source is a media file, ending with one of the following suffix:
https://github.com/cbopp-art/lightcase/blob/master/src/js/lightcase.js#L122

Hope this helps!

**Comment by tapash** [comment]
worked, thanks
