### ISSUE TITLE
Disable the main scroll in desktop

### ISSUE THREAD

**Issue by numanWD** [cbopp-art/lightcase#15]
Hi,

I really like your plugin, It is neat and clean.
I was checking the documentation and I could find a option to disable the scroll in desktop version, to not allow the user to scroll the main content.

Always I can use the hooks but I was wondering if there is a more clean way to achieve that.

In general I would like to use the similar behaviour than in mobile which remove the main scroll.

Thank you

**Comment by cbopp-art** [comment]
Hi

I think you can get this with just implementing a piece of css. If you check out [this part](https://github.com/cbopp-art/lightcase/blob/master/css/lightcase-max-640.css#L18) which is currently only used for the small breakpoint, you could use it for the second breakpoint as well. Consider that the content would disappear because of the content offset. Simplest solution for this is to remove any transparency of the overlay (similar to mobile) or even you could figure out something different to fix the contents position together with ``òverflow: hidden```.

Hope you'll find a suitable way.

**Comment by cbopp-art** [comment]
Did you find a way, can we close this issue?

**Comment by numanWD** [comment]
Thank you, I have used overflow hidden.

**Comment by cbopp-art** [comment]
Okay, so I'm going to close this issue.
