### ISSUE TITLE
novice stuck with mobile display

### ISSUE THREAD

**Issue by stevejharris** [cbopp-art/lightcase#39]
Hi, i have installed the beautiful lightcase, and it's working 100% on the desktop. But on my android mobile (firefox and chrome) the lightcase behaves in a funny way. the test page is johnnyhardstaff.com/wall2.php. the pop ups are only vimeo videos. the video does not size correctly, and the swipe does not work. (i have not tested on apple devices) can you help please? thanks, steve

**Comment by cbopp-art** [comment]
Hi Steve

I will have a look asap! But first of all, did you already ensure having included the jquery.events.touch.js file properly?
 
Regards,
Cornel

**Comment by stevejharris** [comment]
thanks, hopefully this is correct... view-source:http://www.johnnyhardstaff.com/lightcase/vendor/jQuery/jquery.events.touch.js it's there. thanks

**Comment by cbopp-art** [comment]
Hi!
I'm sorry for this late response! I can't fix this issue without workarounds since it is related to detect swipe gestures on iframes.
A possible workaround may could be to overlay the iframe with a ```<div>``` but this can't be implemented permanently within lightcase because we do not know what actually can be the content within the iframe e.g. links, control bars, etc... they wouldn't be clickable anymore.

**Comment by stevejharris** [comment]
hi, thanks for getting back to me, no problem. i see and understand why the swipe wouldn't work. but still the videos do not size like they do on your demo (http://www.johnnyhardstaff.com/wall2.php). also, oddly, my friend says that they do not work at all on his Mac desktop. I'll get back to you with a screengrab and some more info. thanks

**Comment by cbopp-art** [comment]
@stevejharris Please feel free to reopen this issue in case that this is still a common problem with the latest version of lightcase.
