### ISSUE TITLE
Lightbox incompactible with jquery > 3

### ISSUE THREAD

**Issue by VanFanelia** [cbopp-art/lightcase#86]
The function .load() (http://api.jquery.com/load-event/) is removed in jquery 3.
The script ist not compactible with the newest jquery. 

Is there a plan to upgrade it?

Greetings,
Van

Update: 
I downloaded the version from your website. It seems to be an old one. If i use your current script from github it works :)

**Comment by cbopp-art** [comment]
Thank you!
Yeah, last official release was version 2.3.4, the download link on website is pointing to that release, not the master branch.

I will plan a new release quite soon, but I'm still waiting for responses on open issues which I want to close at first.

**Comment by jfeust** [comment]
@cbopp-art Any update on this?  We're evaluating lightbox/modal plugins now and this is preventing us from testing lightcase.

**Comment by cbopp-art** [comment]
@jfeust what issues did you face on which branch/tag so far? Current branch 2.3.x at least seems to work with jQuery 3.0.

**Comment by jfeust** [comment]
@cbopp-art 

When I click an image lightcase opens and I can see the buttons/overlay but it's gets stuck loading the image and gives:

![screen shot 2016-11-15 at 11 10 28 am](https://cloud.githubusercontent.com/assets/732877/20317661/329e2f20-ab24-11e6-9f68-37f4ee0801ef.png)

**Comment by cbopp-art** [comment]
Hmm, this is strange because I cannot reproduce the error you get and all is working fine using the latest jQuery version 3.1.1. Btw: actually `.on('load', function ()` not `.load(function ()` is used to check if the image is loaded.

**Comment by jfeust** [comment]
Looks like the 2.3.4 version on cdnjs might be out of date. If I use the JS from github it works.  But this: https://cdnjs.cloudflare.com/ajax/libs/lightcase/2.3.4/js/lightcase.js  still contains the missing .load function.

**Comment by stebogit** [comment]
Hey @cbopp-art, first of all thanks for this nice library!
I just wanted to add here that also the mobile functionality breaks with jQuery `v3+` because of [incompatibility](https://stackoverflow.com/questions/38497347/jquery-mobile-1-4-5-uncaught-typeerror-cannot-read-property-concat-of-undefin) (still...) with the latest stable jQuery Mobile `v1.4.5`.

This the error:
![screen shot 2017-10-05 at 2 06 29 pm](https://user-images.githubusercontent.com/12717225/31252555-6bd2f242-a9d6-11e7-800c-f045731acdb6.png)
Using jQuery `v2.x` seems to work fine.

Maybe you want to mention it in your docs for the time being, and maybe add the link to [jQuery v2.2.4](https://code.jquery.com/jquery-2.2.4.min.js) for convenience.
